# Site settings
title: SensorBox Documentation
subtitle:
email: 
description: SensorBox Assembly & Usage Documentation
baseurl: 
url: "" # the base hostname & protocol for your site
author: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/nature40
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
